from .account_list import *
from .account_info import *
from .account_tanks import *
from .account_achievements import *
from .auth_login import *
from .auth_prolongate import *
from .auth_logout import *
from .stronghold_claninfo import *
from .stronghold_clanreserves import *
from .stronghold_activateclanreserve import *
from .globalmap_fronts import *
from .globalmap_provinces import *
from .globalmap_claninfo import *
from .globalmap_clanprovinces import *
from .globalmap_clanbattles import *
from .globalmap_seasons import *
from .globalmap_seasonclaninfo import *
from .globalmap_seasonaccountinfo import *
from .globalmap_seasonrating import *
from .globalmap_seasonratingneighbors import *
from .globalmap_events import *
from .globalmap_eventclaninfo import *
from .globalmap_eventaccountinfo import *
from .globalmap_eventaccountratings import *
from .globalmap_eventaccountratingneighbors import *
from .globalmap_eventrating import *
from .globalmap_eventratingneighbors import *
from .globalmap_info import *
from .encyclopedia_vehicles import *
from .encyclopedia_vehicleprofile import *
from .encyclopedia_achievements import *
from .encyclopedia_info import *
from .encyclopedia_arenas import *
from .encyclopedia_provisions import *
from .encyclopedia_personalmissions import *
from .encyclopedia_boosters import *
from .encyclopedia_vehicleprofiles import *
from .encyclopedia_modules import *
from .encyclopedia_badges import *
from .encyclopedia_crewroles import *
from .encyclopedia_crewskills import *
from .clanratings_types import *
from .clanratings_dates import *
from .clanratings_clans import *
from .clanratings_neighbors import *
from .clanratings_top import *
from .tanks_stats import *
from .tanks_achievements import *
from .tanks_mastery import *
from .clans_list import *
from .clans_info import *
from .clans_accountinfo import *
from .clans_glossary import *
from .clans_messageboard import *
from .clans_memberhistory import *
